project_id = "cbezdlqbpebedvpkehjh"

[functions.crypto-chat]
verify_jwt = true

[functions.check-price-alerts]
verify_jwt = false

[functions.nowpayments-deposit]
verify_jwt = true

[functions.fetch-price-history]
verify_jwt = false
