// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-wallet-balances.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_wallet_balances_default = defineTool({
  name: "get_wallet_balances",
  title: "Get wallet balances",
  description: "List the signed-in user's crypto wallet balances (coin symbol and balance) on CTTTradeZone.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("wallet_balances").select("coin_symbol, balance, updated_at").eq("user_id", ctx.getUserId()).order("coin_symbol");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { balances: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-deposit-history.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.1.12";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_deposit_history_default = defineTool2({
  name: "get_deposit_history",
  title: "Get deposit history",
  description: "List the signed-in user's recent deposit records on CTTTradeZone, newest first.",
  inputSchema: {
    limit: z.number().int().describe("Max number of deposits to return (1-100). Defaults to 25.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = Math.max(1, Math.min(100, limit ?? 25));
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("deposit_history").select(
      "id, coin_symbol, wallet_address, amount, transaction_hash, confirmation_status, confirmations, created_at, confirmed_at, notes"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deposits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-transaction-history.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.1.12";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_transaction_history_default = defineTool3({
  name: "get_transaction_history",
  title: "Get transaction history",
  description: "List the signed-in user's recent transactions (deposits, trades, transfers) on CTTTradeZone, newest first.",
  inputSchema: {
    limit: z2.number().int().describe("Max number of transactions to return (1-200). Defaults to 50.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = Math.max(1, Math.min(200, limit ?? 50));
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("transactions").select("id, type, from_symbol, to_symbol, amount, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-coin-prices.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_coin_prices_default = defineTool4({
  name: "get_coin_prices",
  title: "Get coin prices",
  description: "Get the latest cached prices and 24h change for every coin tracked by CTTTradeZone.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("coin_prices").select("symbol, name, price, change_24h, updated_at").order("symbol");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { prices: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cbezdlqbpebedvpkehjh";
var mcp_default = defineMcp({
  name: "ctttradezone-mcp",
  title: "CTTTradeZone",
  version: "0.1.0",
  instructions: "Tools for the signed-in CTTTradeZone user. Use these to read the user's crypto wallet balances, deposit history, transaction history, and current coin prices. All tools act as the signed-in user; all writes are still gated by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_wallet_balances_default, get_deposit_history_default, get_transaction_history_default, get_coin_prices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
